/**
 * stop.js — Stop hook
 *
 * Fires when Claude finishes responding (including before compaction).
 * Does NOT rely on Claude choosing to act — this script writes directly.
 *
 * Logic:
 *   1. Check git diff for uncommitted source file changes
 *   2. If CHANGELOG.md was already updated this session → do nothing
 *   3. If source files changed but CHANGELOG wasn't → append a [DRAFT] skeleton
 *      entry to CHANGELOG.md so the record survives compaction
 *
 * The draft entry lists every changed file. Claude or the user can flesh it
 * out later, but the file list is never lost.
 */

const { execSync } = require('child_process')
const fs = require('fs')
const path = require('path')

const REPO        = 'C:/Users/beemy/Mayil'
const CHANGELOG   = path.join(REPO, 'docs/changelog/CHANGELOG.md')
const CODE_EXT    = /\.(ts|tsx|sql|css|js|jsx)$/
const SKIP        = [/[/\\]\.claude[/\\]/, /node_modules/, /\.next[/\\]/]

function gitLines(cmd) {
  try {
    return execSync(cmd, { cwd: REPO, encoding: 'utf8', stdio: ['pipe', 'pipe', 'ignore'] })
      .trim().split('\n').filter(Boolean)
  } catch {
    return []
  }
}

function currentVersion() {
  try {
    const content = fs.readFileSync(CHANGELOG, 'utf8')
    const match = content.match(/##\s+\[(\d+\.\d+\.\d+)\]/)
    if (!match) return '0.1.0'
    const [major, minor, patch] = match[1].split('.').map(Number)
    return `${major}.${minor}.${patch + 1}`
  } catch {
    return '0.1.0'
  }
}

let raw = ''
process.stdin.on('data', c => { raw += c })
process.stdin.on('end', () => {
  try {
    const unstaged = gitLines('git diff --name-only HEAD')
    const staged   = gitLines('git diff --name-only --cached')
    const all      = [...new Set([...unstaged, ...staged])]

    const sourceFiles = all.filter(f => CODE_EXT.test(f) && !SKIP.some(p => p.test(f)))
    const changelogTouched = all.some(f => /CHANGELOG/i.test(f))

    // Nothing to do
    if (sourceFiles.length === 0 || changelogTouched) {
      process.exit(0)
    }

    // Build a draft entry and prepend it after the header
    const today   = new Date().toISOString().slice(0, 10)
    const version = currentVersion()
    const fileList = sourceFiles.map(f => `- \`${f}\``).join('\n')

    const draft = `\n## [${version}] ${today} — [DRAFT — add description]\n\n` +
      `> **This entry was auto-generated by the Stop hook because CHANGELOG.md was not updated.**\n` +
      `> Replace this block with a proper entry before committing.\n\n` +
      `### Changed\n\n${fileList}\n\n---\n`

    // Insert after the first "---" separator (after the header)
    let content = fs.readFileSync(CHANGELOG, 'utf8')
    const insertAt = content.indexOf('\n---\n')
    if (insertAt !== -1) {
      content = content.slice(0, insertAt + 5) + draft + content.slice(insertAt + 5)
    } else {
      content = content + draft
    }

    fs.writeFileSync(CHANGELOG, content, 'utf8')

    // Output a system message so Claude sees what happened
    const out = {
      systemMessage:
        `[stop-hook] CHANGELOG.md was not updated — a draft entry was auto-written ` +
        `listing ${sourceFiles.length} changed file(s). ` +
        `Replace the [DRAFT] block in docs/changelog/CHANGELOG.md with a proper description.`,
    }
    process.stdout.write(JSON.stringify(out))
  } catch {
    process.exit(0)
  }
})
