-- ============================================================
-- Mayil — Migration 004: Brief content columns
-- Created: 2026-04-14
-- Adds structured content columns to briefs so that the public
-- web brief page and admin editor can render without parsing HTML.
-- ============================================================

-- ── briefs: add summary column ───────────────────────────────
-- 2–3 sentence narrative generated by Claude for each brief.
-- Stored separately so the web brief page doesn't have to parse html_content.
ALTER TABLE briefs
  ADD COLUMN IF NOT EXISTS summary text;

-- ── briefs: add closing_question column ─────────────────────
-- The strategic closing question generated by Claude.
-- Empty string for executive_digest and channel_focus variants;
-- only included in full variant. On baseline briefs, replaced with
-- the orientation prompt.
ALTER TABLE briefs
  ADD COLUMN IF NOT EXISTS closing_question text;

-- ── briefs: add is_baseline flag (if not already in 003) ─────
-- True for Brief #1 of any account. Migration 003 may have already
-- added this; IF NOT EXISTS is safe.
ALTER TABLE briefs
  ADD COLUMN IF NOT EXISTS is_baseline boolean NOT NULL DEFAULT false;
